aws.legacy.host: https://web-app-tuv.is24-legacy.abc.de
aws.realtorbadges.api.host: https://tuv-badges.is24-branchenbuch.eu-west-1.abc.de
roleApiHostConfig.hostAndPathPrefixToAdd: https://tuv-sso.abc.de/api/role/
blacklist.aws.api.host: https://blk.rest.abc.de
checkout.aws.api.host: https://checkout-app-tuv.is24-checkout.abc.de
homeowneracquisition.api.host: https://api-rle.maklersuchmaschine.abc.de
commercial.ontop.adapter.api.host: https://crm-api.gewerbe.abc.de
commservice.api.url: https://sandbox.comm-service.wolke.is/api
de.is24.baufinanzierung.aws.api.host: https://tuv-bau.abc.de
eva.api.aws.host: https://tuv-realtor-evaluation-api.is24-realtor-services.eu-west-1.abc.de
exp.aws.api.host: https://tuv-exp.abc.de
gacApiHostConfig.aws.hostAndPathPrefixToAdd: https://tuv-gac.abc.de/geoautocomplete/v4.0/
gis.aws.api.host: https://tuv-gis.abc.de
marketDataRemoteApiConfig.aws.host: https://tuv-modis-api.abc.de
modis.api.aws.host: https://tuv-modis-web.abc.de
myscoutApiHostConfig.aws.hostAndPathPrefixToAdd: https://tuv-msc.abc.de/meinkonto/api/v1/user/
offer.aws.eco.url: https://tuv-eco.abc.de
offer.aws.oma.url: https://tuv-oma.is24-offer.abc.de
offer.aws.scoutreport.url: https://tuv-scoutreport.abc.de
offer.aws.otoa.url: https://tuv-is24-on-top-offer-app.is24-publication.eu-west-1.abc.de
pda.hostAndPathPrefix: https://pda-test.property-developer.wolke.is
regionSearchApiHostConfig.aws.hostAndPathPrefixToAdd: https://tuv-gac.abc.de/geoautocomplete/
sea.aws.api.host: https://tuv-sea.abc.de
ssa.aws.api.host: https://tuv-ssa.abc.de
sso.aws.api.host: https://tuv-sso.abc.de
tat.host: https://tat.abc.de
valuation.api.aws.host: https://tuv-val.abc.de
targetRent.api.host: https://tuv-target-rent.is24-target-rent.abc.de
referencePrice.api.aws.host: https://tuv-reference-price.abc.de
realtorLeadEngine.api.aws.host: https://realtor-lead-engine-webapp-tuv.maklersuchmaschine.abc.de
naturalTextGenerator.api.aws.host: https://tuv-is24-natural-text-generator.is24-offer.abc.de
contact-api.api.host: https://box-is24-contact-api.is24-contact-api.eu-west-1.abc.de
